[project]
name = "service-algoritm"
version = "0.1.0"
description = "Parsing and visualization microservice"
requires-python = ">=3.13"

dependencies = [

]

[build-system]
requires = ["setuptools>=65.5.1"]
build-backend = "setuptools.build_meta"
